---
title: "Ch 7 - Pg 270 Example - Coef Part Determination"
author: "Adam McQuistan"
date: "Monday, April 18, 2016"
output: pdf_document
---

#Using the body fat data set calculate the the following coefficients of partial determination
* $R^{2} Y 2 | 1$
* $R^{2} Y 3 | 1,2$
* $R^{2} Y 1 | 2$


```{r}
fullRegressionAnova <- function(lm_anova){
  VariationSource <- c("Regression", rownames(lm_anova), "Total")
  SSR <- sum(lm_anova$"Sum Sq"[1:(length(lm_anova$"Sum Sq")-1)])
  SST <- sum(lm_anova$"Sum Sq")
  DFReg <- sum(lm_anova$"Df"[1:(length(lm_anova$"Df")-1)])
  MSE <- lm_anova$"Mean Sq"[length(lm_anova$"Mean Sq")]
  MSR <- SSR / DFReg  
  
  SS <- c(SSR,lm_anova$"Sum Sq",SST)
  MS <- c(MSR, lm_anova$"Mean Sq", NA)
  DF <- c(DFReg, lm_anova$"Df", sum(lm_anova$"Df"))
  F_stat <- MSR / MSE
  F_stats <-c(F_stat, lm_anova$"F value",NA)
  df_out <- data.frame(VariationSource, DF,SS, MS, F_stats)
  print(df_out)
  return(df_out)
}

df <- read.csv("data/ch7_body_fat.csv")

str(df)
```



##$R^{2} Y 2 | 1$

```{r}
full <- lm(Body.Fat ~ X1 + X2, data=df)
reduced <- lm(Body.Fat ~ X1, data = df) 

full_aov <- fullRegressionAnova(anova(full))
reduced_aov <- fullRegressionAnova(anova(reduced))
SSR_X2_given_X1 <- full_aov[3,3]
SSE_reduced <- reduced_aov[3,3]
result_pct <- round(SSR_X2_given_X1 / SSE_reduced * 100, 1)

msg <- paste("Adding in X2 to the model containing X1 reduces the error sum of squares by ", 
             result_pct, " percent", sep="")
cat(msg)
```

##$R^{2} Y 3 | 1,2$


```{r}
full <- lm(Body.Fat ~ X1 + X2 + X3, data=df)
reduced <- lm(Body.Fat ~ X1 + X2, data = df) 

full_aov <- fullRegressionAnova(anova(full))
reduced_aov <- fullRegressionAnova(anova(reduced))

SSR_X3_given_X1X2 <- full_aov[4,3]
SSE_reduced <- reduced_aov[4,3]

result_pct <- round(SSR_X3_given_X1X2 / SSE_reduced * 100, 1)

msg <- paste("Adding in X3 to the model containing X1 and X2 reduces the error sum of squares by ", 
             result_pct, " percent", sep="")
cat(msg)
```


##$R^{2} Y 1 | 2$

```{r}
full <- lm(Body.Fat ~ X2 + X1, data=df)
reduced <- lm(Body.Fat ~ X2, data = df) 

full_aov <- fullRegressionAnova(anova(full))
reduced_aov <- fullRegressionAnova(anova(reduced))

SSR_X1_given_X2 <- full_aov[3,3]
SSE_reduced <- reduced_aov[3,3]

result_pct <- round(SSR_X1_given_X2 / SSE_reduced * 100, 1)

msg <- paste("Adding in X1 to the model containing X2 reduces the error sum of squares by ", 
             result_pct, " percent", sep="")
cat(msg)

```